http:
  routers:
    galactic-sovereign-frontend-https:
      entryPoints:
        - "websecure"
      rule: 'Host(`galactic-sovereign.{{ env "DOMAIN_NAME" }}`) && PathPrefix(`/`)'
      service: galactic-sovereign-frontend
      tls:
        certResolver: letsencryptresolver

  services:
    galactic-sovereign-frontend:
      loadBalancer:
        servers:
          - url: "http://galactic-sovereign-frontend:3001"
